version: "3.9"

services:
  redis:
    image: redis:7
    ports: ["6377:6379"]
    volumes:
      - ./redis:/data

  worker:
    build: ../worker-service
    environment:
      APP_PORT: 8081
      API_KEY: supersecret
      TLS_CERT_FILE: /cert/certificate.pem
      TLS_KEY_FILE: /cert/private.key
    ports:
      - "8081:8081"
    volumes:
      - ../cert:/cert

  agent:
    build: ../agent-service
    environment:
      CONTROLLER_URL: https://controller:8080
      API_KEY: supersecret
      WORKER_URL: https://worker:8081
      REDIS_ADDR: redis:6379
      REDIS_PASS: ""
      REDIS_DB: 0
    depends_on:
      - worker
      - redis