version: "3.9"

services:
  redis:
    image: redis:7
    ports: ["6377:6379"]

  worker:
    build: ../worker-service
    environment:
      APP_PORT: 8081
      API_KEY: supersecret
    ports:
      - "8081:8081"

  agent:
    build: ../agent-service
    environment:
      CONTROLLER_URL: http://controller:8080
      API_KEY: supersecret
      WORKER_URL: http://worker:8081
      REDIS_ADDR: redis:6379
      REDIS_PASS: ""
      REDIS_DB: 0
    depends_on:
      - worker
      - redis