version: "3.9"

volumes:
  postgres:

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: controller
    ports: ["5434:5432"]
    volumes:
      - postgres:/var/lib/postgresql/data

  controller:
    build: ../controller-service
    environment:
      APP_PORT: 8080
      DB_URL: postgres://postgres:postgres@postgres:5432/controller?sslmode=disable
      API_KEY: supersecret
      TLS_CERT_FILE: /cert/certificate.pem
      TLS_KEY_FILE: /cert/private.key
    ports: ["8080:8080"]
    depends_on:
      - postgres
    volumes:
      - ../cert:/cert